{{- if  .Values.customTLS.generateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.customTLS.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.customTLS.crt }}
  tls.key: {{ .Values.customTLS.key }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.customTLS.nameCA }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.pem: {{ .Values.customTLS.crt }}
{{- end }}
