{{- if .Values.ingress.enabled -}}
{{- $ServiceName := .Release.Name -}}
{{- $httpsServicePort := .Values.service.https_port -}}
{{- $sshproxyServicePort := .Values.service.sshproxy_port -}}
{{- $k8sServicePort := .Values.service.k8s_port -}}
{{- $sshtunServicePort := .Values.service.sshtun_port -}}
{{- $IngressPath := .Values.ingress.path -}}
{{- $IngressPathType := .Values.ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $value := .Values.ingress.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts }}
      http:
        paths:
          - path: {{ $IngressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $ServiceName }}
                port:
                  name: "https"
                  number: 443
          - path: {{ $IngressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $ServiceName }}
                port:
                  name: "sshproxy"
                  number: 3023
          - path: {{ $IngressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $ServiceName }}
                port:
                  name: "k8s"
                  number: 3026
          - path: {{ $IngressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $ServiceName }}
                port:
                  name: sshtun
                  number: 3024
          - path: {{ $IngressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $ServiceName }}
                port:
                  name: mysql
                  number: 3036
          - path: {{ $IngressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $ServiceName }}
                port:
                  name: postgres
                  number: 5432
          - path: {{ $IngressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $ServiceName }}
                port:
                  name: mongo
                  number: 27017
          {{- end -}}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}

