.version: &version "12.1.0-dev"

name: teleport-kube-agent
apiVersion: v2
version: *version
appVersion: *version
description: Teleport provides a secure SSH and Kubernetes remote access solution that doesn't get in the way.
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
  - Teleport
